# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1486656286);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1486656406);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1486922778);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1486923018);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1486922898);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1486656526);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1488059020133");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1488060837133");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1488059021207");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1488062621207");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20170118123525");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1488059063");
user_pref("browser.slowStartup.averageTime", 2721);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20170118123525");
user_pref("browser.startup.homepage_override.mstone", "45.7.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1486742206060");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1486655868661");
user_pref("datareporting.policy.firstRunTime", "1486655806060");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.main", 30);
user_pref("datareporting.sessions.current.startTime", "1488059061950");
user_pref("datareporting.sessions.current.totalTime", 4);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.0", "{\"s\":1486655805276,\"a\":48,\"t\":1748,\"c\":true,\"m\":80,\"fp\":3433,\"sr\":3390}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1486922657488,\"a\":65,\"t\":364,\"c\":true,\"m\":140,\"fp\":2504,\"sr\":2378}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1486923434360,\"a\":3,\"t\":13,\"c\":true,\"m\":91,\"fp\":1332,\"sr\":1374}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1487448687265,\"a\":8,\"t\":43,\"c\":true,\"m\":701,\"fp\":3281,\"sr\":3061}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1487945823779,\"a\":1,\"t\":4,\"c\":true,\"m\":750,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1487945825771,\"a\":1,\"t\":7,\"c\":true,\"m\":30,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1488059009766,\"a\":3,\"t\":16,\"c\":true,\"m\":700,\"fp\":2741,\"sr\":2825}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/util/mozilla/lib/firefox-45.7.0esr-x86_64/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.7.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1486656287);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.7.0");
user_pref("extensions.lastPlatformVersion", "45.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/util/mozilla/lib/firefox-45.7.0esr-x86_64/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1484776445000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/util/mozilla/lib/firefox-45.7.0esr-x86_64/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.7.0\",\"st\":1484776444000}}}");
user_pref("gecko.buildID", "20170118123525");
user_pref("gecko.mstone", "45.7.0");
user_pref("idle.lastDailyNotification", 1486656470);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1486655869);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20170126160927");
user_pref("media.gmp-manager.lastCheck", 1486922720);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1486656470);
user_pref("places.history.expiration.transient_current_max_pages", 98667);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("plugin.soname.list", "libXt.so:libXext.so");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1486656470);
user_pref("toolkit.startup.last_success", 1488059061);
user_pref("toolkit.telemetry.cachedClientID", "44ff6bf6-b94b-4329-8de4-e71e8d1b6b87");
user_pref("toolkit.telemetry.previousBuildID", "20170118123525");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
